---
title: MacOS Setup
---

<br>

## MacOS Setup

### VSCode Installation

Download and install [VSCode][vs_code]

<br>

### VSCode Extensions

**Install Benten Extension**

[Open Benten in the marketplace][benten_vs_code_marketplace] and click the `Install` button or follow the directions.

**Install Redhat Yaml VSCode Extension**

[Open RedHad Yaml in the marketplace][redhat_yaml_vs_code_marketplace] and click the `Install` button.

#### Attribute CWL files to the yaml file type

Add the following chunk to the VSCode [user settings json][user_settings_json] to attribute CWL to the YAML file type.

```json
{
    "files.associations": {
        "*.cwl": "yaml"
    }
}
```

<br>

### Docker Installation

[Install docker][docker_install]

<br>

### Install Mamba

Mamba is a faster version of conda.

First install miniforge (this will also install conda)

[Install Miniforge][miniforge_install]

Then install mamba.

[Install Mamba][mamba_install]

<br>

### Conda Setup

#### Update Conda sources configuration

Tell conda about which channels (sources) we will use

```bash
conda config --add channels conda-forge
```

<br>

::::::::::::::::::: callout

### M1 Users

MacOS M1 users may need to ensure `libarchive` (from the conda-forge channel) has first been installed on their conda system before using mamba [^1]

```bash
conda remove -n base libarchive
conda install -y -n base -c conda-forge \
  libarchive 
```

If you continue to have issues, please re-install conda via miniforge (shown above), or just replace the `mamba` commands below with `conda`.  

::::::::::::::::::

#### Create a virtual environment

Create a virtual environment using conda

```bash
mamba create --name cwltutorial python==3.11 mamba
```

<br>

#### Activate the virtual environment

```bash
mamba activate cwltutorial
```

<br>

#### Install prerequisites via Mamba

```bash
mamba install --yes \
  cwltool \
  graphviz \
  wget \
  git \
  nodejs
```

:::::::::::::::: callout

Reactivating the conda virtual environment

The virtual environment needs to be activated every time you start a terminal using
`mamba activate cwltutorial`.

::::::::::::::::

[^1]: [Mamba libarchive Issue][mamba_libarchive_issue]

[mamba_libarchive_issue]: https://github.com/mamba-org/mamba/issues/1826#issuecomment-1196636463
[docker_install]: https://docs.docker.com/desktop/mac/install
[miniforge]: https://github.com/conda-forge/miniforge
[mamba_install]: https://mamba.readthedocs.io/en/latest/installation/mamba-installation.html
[vs_code]: https://code.visualstudio.com/
[benten_vs_code_marketplace]: https://marketplace.visualstudio.com/items?itemName=sbg-rabix.benten-cwl
[redhat_yaml_vs_code_marketplace]: https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml
[user_settings_json]: https://code.visualstudio.com/docs/getstarted/settings#_settingsjson
