## GitHub Requirements

This part assumes you have a GitHub.com account.  

If you do not have a GitHub.com account you can create one [here][github_signup]

The following steps will take you through the process of creating a SSH key pair to 
connect your terminal to GitHub. If you already have this set up, you may skip this part.  


:::::::::::::::::: callout


### Opening files from the terminal

Whenever you are required to open a file from the terminal, you may type `code /path/to/file`.

This will also create the file if it does not yet exist.  

::::::::::::::::::


### SSH Key

After generating an account you will need to generate an SSH Key so that you can pull and push code from your terminal to GitHub.  

In your terminal run the following command

```
# Create the .ssh directory
mkdir -p --mode 700 ~/.ssh

ssh-keygen -f ~/.ssh/github -t ed25519 -q -N ""
```

### Add your public key to GitHub

Head to [GitHub SSH and GPG keys][github_settings].  

Click `New SSH key`.  
set the title as the name of your computer (this can be anything), and under the 'Key', 
copy the contents of `~/.ssh/github.pub` from your terminal.  

### Setting your SSH Config

Open up `~/.ssh/config` and add in the following code chunk:

```
Host github.com
  IdentityFile /home/YOUR_USER_NAME/.ssh/github
  User git
```

### Test your connection

```
ssh -T git@github.com
```

You should see a message like so

```
Hi alexiswl! You've successfully authenticated, but GitHub does not provide shell access.
```

[github_signup]: https://github.com/signup
[github_settings]: https://github.com/settings/keys
